# Generated by Django 3.1.6 on 2021-02-20 19:00

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payer', models.CharField(max_length=30)),
                ('points', models.IntegerField()),
                ('timestamp', models.DateTimeField(default=datetime.datetime(2021, 2, 20, 19, 0, 28, 664319, tzinfo=utc))),
            ],
        ),
    ]
